### ISSUE TITLE
App is not starting

### ISSUE THREAD

**Issue by SandrisJermacans** [nikunjdnp/pm2-free-monitoring#5]
node version v8.15.0

`ubuntu@ip-172-31-80-163:~/pm2-free-monitoring$ node start app.js
module.js:550
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/pm2-free-monitoring/start'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
`

**Comment by nikunjdnp** [comment]
Hey @SandrisIntelZone , I hope you have created .env file (configuration file which contains pm2/database ip addresses) under `pm2-free-monitoring` folder.

If you did not create, Please make a file with `.env` and copy & paste below the content:

DB_HOST= your_database_ip
DB_USER=your_database_username
DB_PASS=your_database_password
PM2_IP=IP_of_the_instance_where_pm2_is_running
DB_NAME=your_influx_database_name

Just replace these values with your actual values.  

let me know if you are still facing this issue.

**Comment by SandrisJermacans** [comment]
I have created the .env file but getting the same error

![pm2capture](https://user-images.githubusercontent.com/39297130/50957582-dae08600-14be-11e9-8f61-f350b6a6ddb9.PNG)

**Comment by nikunjdnp** [comment]
Hi @SandrisIntelZone, 

Now, start app with `node app.js`. Let me know if your issue is resolved or not.

**Comment by SandrisJermacans** [comment]
Yes, it works. Thank you!
