### ISSUE TITLE
Pm2 web has been deprecated.

### ISSUE THREAD

**Issue by SutharMukesh** [nikunjdnp/pm2-free-monitoring#8]
Pm2 removed pm2 web interface in version 4.x. [reference link](https://github.com/Unitech/pm2/issues/4547#issuecomment-567560063)

our metrics collector was based on the web interface api json.
Is there any workaround for this problem without degrading to lower version of pm2?

I've forked your project and was using it for a while. would appreciate your help in the same

Thanks

**Comment by nikunjdnp** [comment]
Hi @SutharMukesh, I have seen the pm2 updated APIs. Thus, they have disabled to the pm2 web command and are promoting pm2 plus. As pm2 has removed the command, I suggest you stick with the older versions.

Thanks.

**Comment by SutharMukesh** [comment]
okay Nikunj, 
as of now, would stick with the lower version.
Thanks
